def class Constants {
def static orderings = asText(
	["best"],
	["worst"]
)

def static champions = asText(
	["Aatrox"],
	["Ahri"],
	["Akali"],
	["Alistar"],
	["Amumu"],
	["Anivia"],
	["Annie"],
	["Ashe"],
	["Blitzcrank"],
	["Brand"],
	["Caitlyn"],
	["Cassiopeia"],
	["Chogath", "Cho'Gath"],
	["Corki"],
	["Darius"],
	["Diana"],
	["Draven"],
	["DrMundo", "Dr. Mundo"],
	["Elise"],
	["Evelynn"],
	["Ezreal"],
	["FiddleSticks"],
	["Fiora"],
	["Fizz"],
	["Galio"],
	["Gangplank"],
	["Garen"],
	["Gragas"],
	["Graves"],
	["Hecarim"],
	["Heimerdinger"],
	["Irelia"],
	["Janna"],
	["JarvanIV", "Jarvan IV"],
	["Jax"],
	["Jayce"],
	["Jinx"],
	["Karma"],
	["Karthus"],
	["Kassadin"],
	["Katarina"],
	["Kayle"],
	["Kennen"],
	["Khazix", "Kha'Zix"],
	["KogMaw", "Kog'Maw"],
	["Leblanc", "LeBlanc"],
	["LeeSin", "Lee Sin"],
	["Leona"],
	["Lissandra"],
	["Lucian"],
	["Lulu"],
	["Lux"],
	["Malphite"],
	["Malzahar"],
	["Maokai"],
	["MasterYi", "Master Yi"],
	["MissFortune", "Miss Fortune"],
	["MonkeyKing", "Wukong"],
	["Mordekaiser"],
	["Morgana"],
	["Nami"],
	["Nasus"],
	["Nautilus"],
	["Nidalee"],
	["Nocturne"],
	["Nunu"],
	["Olaf"],
	["Orianna"],
	["Pantheon"],
	["Poppy"],
	["Quinn"],
	["Rammus"],
	["Renekton"],
	["Rengar"],
	["Riven"],
	["Rumble"],
	["Ryze"],
	["Sejuani"],
	["Shaco"],
	["Shen"],
	["Shyvana"],
	["Singed"],
	["Sion"],
	["Sivir"],
	["Skarner"],
	["Sona"],
	["Soraka"],
	["Swain"],
	["Syndra"],
	["Talon"],
	["Taric"],
	["Teemo"],
	["Thresh"],
	["Tristana"],
	["Trundle"],
	["Tryndamere"],
	["TwistedFate", "Twisted Fate"],
	["Twitch"],
	["Udyr"],
	["Urgot"],
	["Varus"],
	["Vayne"],
	["Veigar"],
	["Vi"],
	["Viktor"],
	["Vladimir"],
	["Volibear"],
	["Warwick"],
	["Xerath"],
	["XinZhao", "Xin Zhao"],
	["Yorick"],
	["Zac"],
	["Zed"],
	["Ziggs"],
	["Zilean"],
	["Zyra"]
)

def static regions = asText(
	["NA"],
	["EUW"],
	["EUNE"],
	["BR"],
	["TR"],
	["RU"],
	["LAN"],
	["LAS"],
	["OCE"]
)

def static seasons = asText(
	["season3", "Season 3"],
	["season4", "Seaons 4"]
)

def static asText(Object... values) {
	def result = [:]
	values.each{
		value ->
			def key = value[0]
			def name = value.size() == 2 ? value[1] : key.capitalize()
			result[key] = [
				name: name,
				path: name.toLowerCase().replace("'", "-").replace(" ", "-")
			]
	}
	result
}
}
